live_config_reload: true
window: 
  opacity: 1

scrolling:
    history: 10000

url:
    launcher: xdg-open

font:
  normal:
    family: "Roboto Mono"

  bold:
    family: "Roboto Mono"

  italic:
    family: "Roboto Mono"

  size: 16

  # One Dark
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xafaea3'

  # Normal colors
  normal:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x0000ff'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'

  # Bright colors
  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    blue:    '0x0000ff'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xffffff'
