# Set ZSH options
setopt correct     # correct typos in commands

# Custom Environment Variables
export PATH="$PATH:$HOME/.local/bin:/usr/local/texlive/2021/bin/x86_64-linux"
export EDITOR="vim"
export LS_COLORS="$(vivid generate one-dark || echo '')"
export LANG="en_US.UTF-8"
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export CUR_TERM=$(basename `/usr/bin/cat /proc/$PPID/comm`)
export GPG_TTY=$TTY
export KEYTIMEOUT=1
export SUDO_ASKPASS='/bin/ksshaskpass'
export MAKEFLAGS="-j $(nproc)"

# add android dev tools to PATH for react-native
export ANDROID_HOME=$HOME/Android/Sdk
export ANDROID_SDK_ROOT=$ANDROID_HOME
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Custom Aliases
alias cat=bat
alias fdu='du -hc --max-depth=1 | sort -hr'
alias df='df -h'
alias pacman='sudo pacman'
alias sudo='sudo '
alias dust='dust -rb'

